name: cladeomatic
channels:
  - defaults
dependencies:
  - python=3.9
  - snp-dists
  - numpy>=1.23.0
  - pandas>=2.0.1
  - biopython>=1.81
  - six>=1.16.0
  - matplotlib>=3.7.1
  - statistics>=1.0.3.5
  - plotly>=5.14.1
  - ete3==3.1.2
  - jellyfish
  - DendroPy==4.5.2
  - ray>=2.3.1
  - deprecated>=1.2.13
  - psutil==5.9.1
  - scikit-learn>=1.1.1
  - scipy>=1.10.1
  - pyahocorasick>=1.4.4